from app.spatial.errors import (
    GeometryError,
    InvalidDurationError,
    InvalidSpeedError,
    UnknownPlayerError,
)
from app.spatial.goals import direction_to_goal, distance_to_goal, goal_mouth_segment
from app.spatial.movement import (
    clamp_to_field,
    distance_to_nearest_boundary,
    forward_progress,
    is_inside_field,
    move_toward,
    position_after,
    required_speed,
    required_velocity,
    travel_time,
)
from app.spatial.queries import (
    nearest_opponent,
    nearest_player,
    nearest_teammate,
    opponents,
    players_sorted_by_distance,
    players_within_radius,
    teammates,
)
from app.spatial.segments import (
    closest_point_on_segment,
    distance_to_segment,
    is_within_segment_corridor,
    projection_fraction,
    segment_length,
)
from app.spatial.vector import (
    EPSILON,
    add,
    almost_equal,
    direction,
    distance,
    dot,
    interpolate,
    magnitude,
    normalize,
    orientation_degrees,
    scale,
    subtract,
)
from app.spatial.zones import contains_point, distance_to_zone, nearest_point_in_zone

__all__ = [
    "EPSILON",
    "GeometryError",
    "InvalidDurationError",
    "InvalidSpeedError",
    "UnknownPlayerError",
    "add",
    "almost_equal",
    "clamp_to_field",
    "closest_point_on_segment",
    "contains_point",
    "direction",
    "direction_to_goal",
    "distance",
    "distance_to_goal",
    "distance_to_nearest_boundary",
    "distance_to_segment",
    "distance_to_zone",
    "dot",
    "forward_progress",
    "goal_mouth_segment",
    "interpolate",
    "is_inside_field",
    "is_within_segment_corridor",
    "magnitude",
    "move_toward",
    "nearest_opponent",
    "nearest_player",
    "nearest_point_in_zone",
    "nearest_teammate",
    "normalize",
    "opponents",
    "orientation_degrees",
    "players_sorted_by_distance",
    "players_within_radius",
    "position_after",
    "projection_fraction",
    "required_speed",
    "required_velocity",
    "scale",
    "segment_length",
    "subtract",
    "teammates",
    "travel_time",
]
